{
  config,
  flake,
  lib,
  modulesPath,
  options,
  ...
}:

let
  inherit (lib) types;
  inherit (lib.attrsets) setAttrByPath;
  inherit (lib.lists) singleton;
  inherit (lib.modules)
    mkBefore
    mkIf
    mkMerge
    mkOrder
    ;
  inherit (lib.options) mkEnableOption mkOption;
  inherit (lib.strings) escapeShellArg optionalString;

  inherit (flake.outputs.lib.modules) mkFullAlias;

  esc = escapeShellArg;

  cfg = antidoteCfg.ohMyZsh;
  antidoteCfg = zshCfg.antidote;
  omzCfg = zshCfg.oh-my-zsh;
  zshCfg = config.programs.zsh;

  pluginsOptName = modName: [
    "programs"
    "zsh"
    modName
    "plugins"
  ];
  myCond = antidoteCfg.enable && cfg.enable;
in
{

  _class = "homeManager";

  options.programs.zsh.antidote.ohMyZsh = {

    enable = mkEnableOption ''
      loading Oh My ZSH plugins via
      [get-antidote/use-omz](https://github.com/getantidote/use-omz).

      According to the antidote authors,
      this is expected to be faster than enabling Oh My ZSH directly,
      as {option}`programs.zsh.oh-my-zsh.enable` would do it.

      Use the typical Oh My ZSH options, the following are supported:
      - {option}`programs.zsh.oh-my-zsh.custom`
      - {option}`programs.zsh.oh-my-zsh.extraConfig`
      - {option}`programs.zsh.oh-my-zsh.package`
      - {option}`programs.zsh.oh-my-zsh.plugins`
        (order priorities are preserved,
        but entries with order<=500 may not load correctly)
      - {option}`programs.zsh.oh-my-zsh.theme`

      Defaults to loading use-omz from GitHub.
    ''; # <- no dot because mkEnableOption

    useOmzSource = mkOption {
      type = types.str;
      default = "getantidote/use-omz";
      description = ''
        Where antidote should load use-omz from.

        Follows the same specification as all other entries from
        {option}`programs.zsh.antidote.plugins`.

        Defaults to loading it dynamically from GitHub.
      '';
    };

  };

  config = mkIf myCond (mkMerge [

    # assertions
    {
      assertions = singleton {
        assertion = !cfg.enable || !omzCfg.enable;
        message = "Disable programs.zsh.oh-my-zsh.enable when you want to load Oh My ZSH plugins using antidote.";
      };
    }

    # load Oh My ZSH according to getantidote/omz
    {
      # outer mkOrder has higher rank than inner mkBefore
      programs.zsh.antidote.plugins = mkBefore [ cfg.useOmzSource ];
    }

    # translate plugin list, preserving file source & order priorities
    (mkFullAlias {
      loc = pluginsOptName "oh-my-zsh";
      option = options.programs.zsh.oh-my-zsh.valueMeta.configuration.options.plugins;
      apply = map (p: "${esc omzCfg.package}/share/oh-my-zsh path:plugins/${esc p}");
      wrap = setAttrByPath (pluginsOptName "antidote");
      keepOverridePriority = false;
    })

    # apply oh-my-zsh options like ./oh-my-zsh.nix
    # differences are:
    # - apply options at order=540 (before ./antidote.nix loads the plugins)
    # - do not source OMZ
    # - do not set plugins=
    (
      let
        inherit (import "${modulesPath}/programs/zsh/lib.nix" { inherit config lib; }) dotDirRel;
      in
      {

        home = {
          packages = singleton omzCfg.package;
          file = {
            "${dotDirRel}/.zshenv".text = ''
              ZSH=${escapeShellArg omzCfg.package}/share/oh-my-zsh;
              ZSH_CACHE_DIR=${escapeShellArg config.xdg.cacheHome}/oh-my-zsh;
            '';
            "${config.xdg.cacheHome}/oh-my-zsh/.keep".text = "";
          };
        };

        programs.zsh.initContent = mkOrder 540 ''
          # oh-my-zsh extra settings for plugins
          ${omzCfg.extraConfig}
          # oh-my-zsh configuration generated by NixOS
          ${optionalString (omzCfg.custom != "") "ZSH_CUSTOM=${escapeShellArg omzCfg.custom}"}
          ${optionalString (omzCfg.theme != "") "ZSH_THEME=${escapeShellArg omzCfg.theme}"}
        '';

      }
    )

  ]);

}
